# List persons, should return 4 persons with the test database
GET http://127.0.0.1:3001/api/persons

###

# Delete an existing person, should return 204 with the test database
DELETE http://127.0.0.1:3001/api/persons/4

###

# Delete a non-existing person, should return 404 with the test database
DELETE http://127.0.0.1:3001/api/persons/42

###

# List persons, should return 3 persons with the test database
GET http://127.0.0.1:3001/api/persons
