#
# Render requests
#

# List persons, should return 4 persons with the test database
GET https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons

###

# Delete an existing person, should return 204 with the test database
DELETE https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons/4

###

# Delete a non-existing person, should return 404 with the test database
DELETE https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons/42

###

# List persons, should return 3 persons with the test database
GET https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
