#
# Render requests
#

# List persons, should return 4 persons with the test database
GET https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons

###

# Add a person, should return 201
POST https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Tiku Orava",
  "number": "555-0001"
}

###

# Add a person, should fail with return code 400 because of missing body
POST https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
Content-Type: application/json

{
  
}

###

# Add a person, should fail with return code 400 because of missing name
POST https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
Content-Type: application/json

{
  "number": "555-0002"
}

###

# Add a person, should fail with return code 400 because of missing number
POST https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Taku Orava"
}

###

# Add a person, should fail with return code 400 because of a duplicate name
POST https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Tiku Orava",
  "number": "555-0001"
}

###

# List persons, should return 5 persons with the test database
GET https://fullstackopen-harjoitukset-osa3.onrender.com/api/persons
